spring:
  application:
    name: paky-bot

  jackson:
    default-property-inclusion: NON_EMPTY

  liquibase:
    enabled: false
    change-log: classpath:db.changelog/changelog_config.yaml

api:
  ozon:
    url: https://api.ozon.ru
    key: test
  wildberries:
    url: https://suppliers-api.wildberries.ru
    key: test
  yandex-market:
    url: https://api.partner.market.yandex.ru
    key: test

telegram:
  bot:
    token: test
    username: test

ai:
  open-ai:
    key: test
    url: https://api.openai.com
    model: gpt-4o
  azure-vision:
    endpoint: test
    key: test
  perplexity:
    key: test
    url: https://api.perplexity.ai
    model: sonar

logging:
  level:
    org.zalando.logbook: TRACE
    com.shveed.paky.bot.server.service.OpenAIVisionService: DEBUG
    com.shveed.paky.bot.server.service.PerplexityVisionService: DEBUG
    # Feign client logging
    com.shveed.paky.bot.api.openai.OpenAIApi: DEBUG
    com.shveed.paky.bot.api.perplexity.PerplexityApi: DEBUG
    com.shveed.paky.bot.api.marketplaces.ozon.OzonApi: DEBUG
    com.shveed.paky.bot.api.marketplaces.wildberries.WildberriesApi: DEBUG
    com.shveed.paky.bot.api.marketplaces.yandexmarket.YandexMarketApi: DEBUG

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
    parameters:
      - key
      - token
