spring:
  application:
    name: paky-bot

  liquibase:
    enabled: false
    change-log: classpath:db.changelog/changelog_config.yaml

api:
  ozon: o
  wildberries: o

telegram:
  bot:
    token: test
    username: test
