spring:
  application:
    name: paky-bot

  liquibase:
    enabled: false
    change-log: classpath:db.changelog/changelog_config.yaml

api:
  ozon: 
    url: https://api.ozon.ru
    key: test
  wildberries: 
    url: https://suppliers-api.wildberries.ru
    key: test
  yandex-market:
    url: https://api.partner.market.yandex.ru
    key: test

telegram:
  bot:
    token: test
    username: test

ai:
  open-ai:
    key: test
    url: https://api.openai.com
    model: gpt-4o
  azure-vision:
    endpoint: test
    key: test
  perplexity:
    key: test
    url: https://api.perplexity.ai
    model: sonar
