server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/paky-bot
    username: paky-bot
    password: paky-bot

  liquibase:
    enabled: true
    user: paky-bot
    password: paky-bot

  jpa:
    properties:
      hibernate:
        show_sql: true

telegram:
  bot:
    token: ${TELEGRAM_BOTTOKEN}
    username: ${TELEGRAM_USERNAME}
